<a href="https://colab.research.google.com/github/kariukidan/PLP_Academy/blob/main/Assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from pandas import *
from scipy import stats
import numpy as np

In [ ]:
df = read_csv('/content/customer_demographics.csv')

In [ ]:
df.head()

,customer_id,age_range,marital_status,rented,family_size,no_of_children,income_bracket
0,1,70+,Married,0,2,NaN,4
1,6,46-55,Married,0,2,NaN,5
2,7,26-35,NaN,0,3,1,3
3,8,26-35,NaN,0,4,2,6
4,10,46-55,Single,0,1,NaN,5

In [ ]:
clean_df = df.dropna()

In [ ]:
clean_df.head()

,customer_id,age_range,marital_status,rented,family_size,no_of_children,income_bracket
16,31,36-45,Single,0,5+,3+,2
17,33,46-55,Married,0,5+,3+,9
22,40,56-70,Married,0,4,2,7
24,42,26-35,Married,0,4,2,9
25,45,46-55,Married,0,5+,3+,1

In [ ]:
# convert age range to numeric value
def convert_age_range_to_numeric(age_range):
    if age_range == '70+':
        return 70
    else:
        mini, maxi = age_range.split('-')
        return (int(mini) + int(maxi)) / 2

# Apply the conversion function to create a new column
clean_df['age_numeric'] = clean_df['age_range'].apply(convert_age_range_to_numeric)

print(clean_df)

     customer_id age_range marital_status  rented family_size no_of_children  \
16            31     36-45         Single       0          5+             3+
17            33     46-55        Married       0          5+             3+
22            40     56-70        Married       0           4              2
24            42     26-35        Married       0           4              2
25            45     46-55        Married       0          5+             3+
..           ...       ...            ...     ...         ...            ...
738         1529     46-55        Married       0          5+             3+
740         1534     36-45        Married       0           3              1
742         1538     36-45        Married       0          5+             3+
749         1558     36-45        Married       0           3              1
756         1578     46-55        Married       0           3              1

     income_bracket  age_numeric
16                2         40.5
17                9         50.5
22                7         63.0
24                9         30.5
25                1         50.5
..              ...          ...
738               9         50.5
740               5         40.5
742               8         40.5
749               6         40.5
756               6         50.5

[165 rows x 8 columns]

<ipython-input-7-f8291da15bdf>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['age_numeric'] = clean_df['age_range'].apply(convert_age_range_to_numeric)

In [ ]:
# Shapiro-Wilk Test for Normalityif age_range_normality.pvalue > 0.05:
age_range_normality = stats.shapiro(clean_df['age_numeric'])
print(age_range_normality)
if age_range_normality.pvalue > 0.05:
    print("The data is normally distributed :fail to reject hypothesis)")
else:
    print("The data is not normally distributed : reject hypothesis)")

ShapiroResult(statistic=0.9078533053398132, pvalue=1.1260836707549515e-08)
The data is not normally distributed : reject hypothesis)

In [ ]:
#Pearson's chi-square test of goodness-of-fit
age_range_normality= stats.normaltest(clean_df['age_numeric'])
print(age_range_normality)

NormaltestResult(statistic=1.4740844044865145, pvalue=0.47852721108093255)

In [ ]:
#find the skewness of the sample
stats.skew(clean_df['age_numeric'], bias=True)

0.2119585695446123

In [ ]:
#kurtosis of the sample
stats.kurtosis(clean_df['age_numeric'], fisher=True)

0.05164653214948922

In [ ]:
#standard deviation
std_deviation = clean_df['age_numeric'].std()
print(std_deviation)

10.062289371995071

In [ ]:
#convert family size data to numeric values
def convert_size_to_numeric(family_size):
    if family_size == '5+':
        return 5
    else:
        return int(family_size)

# Apply the conversion function to create a new column
clean_df['family_size_numeric'] = clean_df['family_size'].apply(convert_size_to_numeric)

print(clean_df)

     customer_id age_range marital_status  rented family_size no_of_children  \
16            31     36-45         Single       0          5+             3+
17            33     46-55        Married       0          5+             3+
22            40     56-70        Married       0           4              2
24            42     26-35        Married       0           4              2
25            45     46-55        Married       0          5+             3+
..           ...       ...            ...     ...         ...            ...
738         1529     46-55        Married       0          5+             3+
740         1534     36-45        Married       0           3              1
742         1538     36-45        Married       0          5+             3+
749         1558     36-45        Married       0           3              1
756         1578     46-55        Married       0           3              1

     income_bracket  age_numeric  family_size_numeric
16                2         40.5                    5
17                9         50.5                    5
22                7         63.0                    4
24                9         30.5                    4
25                1         50.5                    5
..              ...          ...                  ...
738               9         50.5                    5
740               5         40.5                    3
742               8         40.5                    5
749               6         40.5                    3
756               6         50.5                    3

[165 rows x 9 columns]

<ipython-input-12-89a873c579f3>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['family_size_numeric'] = clean_df['family_size'].apply(convert_size_to_numeric)

In [ ]:
family_size_normality = stats.shapiro(clean_df['family_size_numeric'])
print(family_size_normality)
if family_size_normality.pvalue > 0.05:
    print("The data is normally distributed :fail to reject hypothesis)")
else:
    print("The data is not normally distributed : reject hypothesis)")

ShapiroResult(statistic=0.8004116415977478, pvalue=9.742485545518806e-14)
The data is not normally distributed : reject hypothesis)

In [ ]:
#find the skewness of the sample
stats.skew(clean_df['family_size_numeric'], bias=True)

0.16851520199016332

In [ ]:
#kurtosis of the sample
stats.kurtosis(clean_df['family_size_numeric'], fisher=True)

-1.3753048882354901

In [ ]:
#standard deviation
std_deviation = clean_df['family_size_numeric'].std()
print(std_deviation)

0.9186416270909946